name: run-tracker

on:
  workflow_dispatch:

jobs:
  run-tracker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.RADIUS_APP_ID }}
          private-key: ${{ secrets.RADIUS_ID_KEY }}
          owner: ${{ github.repository_owner }}
      
      - name: Add cache version to environment
        id: radius-cache-version
        run: |
          echo "radius_cache_version=$(npx radius-tracker cache_version)" >> "$GITHUB_ENV"


      - name: Add token to configuration
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: | 
          sed -i "s/github.com/$GH_TOKEN:$GH_TOKEN@github.com/g" radius-tracker.config.js
          

      - name: Restore cache for tracker
        id: cache-radius-tracker
        uses: actions/cache/restore@v4        
        with: 
          key: cache-radius-tracker-${{github.env.radius-cache-version}}-${{hashFiles('radius-tracker.config.js')}}
          path: radius-tracker-cache
          restore-keys: |
            cache-radius-tracker-${{github.env.radius_cache_version}}-${{hashFiles('radius-tracker.config.js')}}

      - name: Run the tracker
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          npx radius-tracker timelines ./radius-tracker.config.js

      - name: Save cache for tracker
        uses: actions/cache/save@v4        
        with: 
          key: cache-radius-tracker-${{github.env.radius-cache-version}}-${{hashFiles('radius-tracker.config.js')}}-${{github.run_id}}    
          path: radius-tracker-cache
      
      - name: Upload database artifact
        uses: actions/upload-artifact@v4
        with:
          name: tracker-database
          path: usages.sqlite.gz
          
          
  build-static-site:
    runs-on: ubuntu-latest
    needs: run-tracker
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: tracker-database

      - name: Generate static site
        run: |
          npx radius-tracker report --database usages.sqlite.gz
      
      - name: Upload static site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: radius-tracker-report/

  deploy-to-github-pages:
    runs-on: ubuntu-latest
    needs: build-static-site

    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
      
    steps:
      - name: Deploy to GitHub Pages
        id: deploy-pages
        uses: actions/deploy-pages@v4
